# Generated by Django 2.2.16 on 2022-03-30 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20220328_1919'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='follower_not_author',
        ),
    ]
